name: Deploy para Render via Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build e push da imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/monolito-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/monolito-backend:latest

      - name: Notificar Render (Opcional)
        run: |
          echo "A imagem Docker foi atualizada no Docker Hub. Certifique-se de que o Render está configurado corretamente para puxar a imagem mais recente."
